Repository NorthGateVologda/NorthGateWeb, pull requests merged in 2023-08, with the labels that each got.

#22 Удалил папку src
  src/api.auth.js
  src/api.city.js
  src/api.config.js
  src/components/Auth/Auth.js
  src/components/Auth/Auth.module.css
  src/components/UI/GeoJson/GeoJson.js
  src/components/UI/Spinner/Spinner.js
  src/components/UI/Spinner/Spinner.module.css
Labels: enhancement

#23 Рефакторинг кода. Исправление ошибок. Сделал выпадающий список вместо…
  app/page.tsx
  entities/diagram/api/ratingPolygonApi.ts
  entities/hexagons/api/hexagonsApi.ts
  entities/map-layer/ui/houses/insex.tsx
  entities/sidebar/ui/tooltip/index.module.css
  entities/sidebar/ui/tooltip/index.tsx
  entities/table/ui/filter/index.module.css
  entities/table/ui/filter/index.tsx
  widgets/authentication/index.tsx
  widgets/map/index.tsx
  widgets/sidebar/index.module.css
  widgets/sidebar/index.tsx
  widgets/table/columns.ts
  widgets/table/index.tsx
Labels: enhancement

#28 Ещё доработки сайта от Виктора
  app/page.tsx
  entities/diagrams/buildings/ui/index.tsx
  entities/diagrams/numOfParks/ui/index.module.css
  entities/diagrams/population/ui/index.module.css
  entities/diagrams/populationPolygonsEffect/ui/index.tsx
  entities/diagrams/ratingPolygonsEffect/ui/index.module.css
  entities/diagrams/ratingPolygonsEffect/ui/index.tsx
  entities/diagrams/recommendPolygons/ui/index.module.css
  entities/map-layer/api/geoJsonApi.ts
  entities/sidebar/ui/filter-table-dropdown/index.tsx
  entities/user/api/authApi.ts
  package-lock.json
  package.json
  shared/ui/base-modal/index.tsx
  widgets/excel/index.tsx
  widgets/sidebar/index.module.css
  widgets/sidebar/index.tsx
  widgets/sidebar/type.ts
  widgets/table/columns.ts
  widgets/table/index.module.css
  widgets/table/index.tsx
  widgets/table/type.ts
Labels: enhancement

#29 Вернул зависимость
  package-lock.json
  package.json
  widgets/table/index.tsx
Labels: bug, enhancement

#31 Добавили скрипты деплоя
  Dockerfile
  deploy.sh
  undeploy.sh
Labels: enhancement

#30 Исправили отображение кнопки
  app/page.tsx
  entities/sidebar/ui/info/index.module.css
  entities/sidebar/ui/info/index.tsx
  package-lock.json
  widgets/map/index.module.css
  widgets/sidebar/index.module.css
  widgets/sidebar/index.tsx
  widgets/table/columns.ts
  widgets/table/index.module.css
  widgets/table/index.tsx
Labels: bug, enhancement

#32 Добавил important из за базового компонента
  widgets/table/index.module.css
Labels: bug, enhancement

#33 Решили проблему с инкрементальной сборкой образа
  Dockerfile
Labels: enhancement

#34 Доработка
  widgets/sidebar/index.tsx
Labels: bug
